<?php
namespace Civi\ConfigManager\Util;

/**
 * Small YAML helper.
 *
 * Symfony YAML is the preferred parser/dumper and is a runtime dependency of
 * this extension. The extension explicitly loads its own Composer autoloader
 * when CiviCRM/CMS has not already loaded Symfony YAML. ext-yaml remains a
 * supported read fallback. Reading without a real YAML parser fails closed.
 */
class SimpleYaml {
  private static bool $runtimeAutoloadAttempted = FALSE;

  /**
   * @param array<string|int, mixed> $data
   */
  public static function dump(array $data): string {
    if (self::loadSymfonyYaml()) {
      return self::normaliseYamlOutput(\Symfony\Component\Yaml\Yaml::dump($data, 8, 2));
    }
    return self::normaliseYamlOutput(self::dumpValue($data, 0) . "\n");
  }

  /**
   * Normalise YAML generated by different libraries so exported files stay
   * easier to read and do not switch between `~` and `null` for empty values.
   */
  private static function normaliseYamlOutput(string $yaml): string {
    $yaml = preg_replace('/^---\s*\R/', '', $yaml);
    $yaml = preg_replace('/\R\.\.\.\s*$/', "\n", $yaml);
    $yaml = preg_replace('/(:\s*)~(\s*(?:#.*)?$)/m', '$1null$2', $yaml);
    $yaml = preg_replace('/(^\s*-\s*)~(\s*(?:#.*)?$)/m', '$1null$2', $yaml);
    return rtrim($yaml) . "\n";
  }

  /**
   * Report the YAML parser available to web/CLI runtime.
   *
   * @return array{available:bool,parser:string,reason:string}
   */
  public static function runtimeStatus(): array {
    if (self::loadSymfonyYaml()) {
      return ['available' => TRUE, 'parser' => 'symfony/yaml', 'reason' => ''];
    }
    if (function_exists('yaml_parse_file')) {
      return ['available' => TRUE, 'parser' => 'ext-yaml', 'reason' => ''];
    }
    return [
      'available' => FALSE,
      'parser' => '',
      'reason' => 'No YAML parser is available. Run Composer in the extension directory to install the PHP 7.4-compatible runtime dependencies, or enable the PHP yaml extension.',
    ];
  }

  /**
   * @return array<string|int, mixed>
   */
  public static function parseFile(string $file): array {
    if (self::loadSymfonyYaml()) {
      $data = \Symfony\Component\Yaml\Yaml::parseFile($file);
      return is_array($data) ? $data : [];
    }
    if (function_exists('yaml_parse_file')) {
      $data = yaml_parse_file($file);
      return is_array($data) ? $data : [];
    }

    throw new \RuntimeException(
      'No YAML parser is available. Configuration Manager requires its bundled Symfony YAML runtime dependency or the PHP yaml extension.'
    );
  }

  /**
   * Load the extension-local Composer autoloader when the host application has
   * not already made Symfony YAML available.
   */
  private static function loadSymfonyYaml(): bool {
    if (class_exists('Symfony\\Component\\Yaml\\Yaml')) {
      return TRUE;
    }

    if (!self::$runtimeAutoloadAttempted) {
      self::$runtimeAutoloadAttempted = TRUE;
      $autoload = dirname(__DIR__, 3) . '/vendor/autoload.php';
      if (is_file($autoload)) {
        require_once $autoload;
      }
    }

    return class_exists('Symfony\\Component\\Yaml\\Yaml');
  }

  /**
   * @param mixed $value
   */
  private static function dumpValue($value, int $indent): string {
    if (is_array($value)) {
      return self::dumpArray($value, $indent);
    }
    return self::scalar($value);
  }

  /**
   * @param array<string|int, mixed> $array
   */
  private static function dumpArray(array $array, int $indent): string {
    $lines = [];
    $isList = array_keys($array) === range(0, count($array) - 1);
    foreach ($array as $key => $value) {
      $pad = str_repeat(' ', $indent);
      if ($isList) {
        if (is_array($value)) {
          $lines[] = $pad . '-';
          $lines[] = self::dumpValue($value, $indent + 2);
        }
        else {
          $lines[] = $pad . '- ' . self::scalar($value);
        }
      }
      else {
        if (is_array($value)) {
          $lines[] = $pad . self::key($key) . ':';
          $lines[] = self::dumpValue($value, $indent + 2);
        }
        else {
          $lines[] = $pad . self::key($key) . ': ' . self::scalar($value);
        }
      }
    }
    return implode("\n", $lines);
  }

  /**
   * @param mixed $key
   */
  private static function key($key): string {
    return preg_match('/^[A-Za-z0-9_.-]+$/', (string) $key) ? (string) $key : self::scalar((string) $key);
  }

  /**
   * @param mixed $value
   */
  private static function scalar($value): string {
    if ($value === NULL) {
      return 'null';
    }
    if ($value === TRUE) {
      return 'true';
    }
    if ($value === FALSE) {
      return 'false';
    }
    if (is_int($value) || is_float($value)) {
      return (string) $value;
    }
    $value = (string) $value;
    if ($value === '') {
      return "''";
    }
    if (strpos($value, "\n") !== FALSE) {
      $lines = explode("\n", $value);
      return "|\n    " . implode("\n    ", $lines);
    }
    return json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
  }
}
