<?php
namespace Civi\ConfigManager\Util;

/**
 * YAML runtime helper.
 *
 * Official release packages bundle Symfony YAML and that is the preferred
 * parser/dumper. Source checkouts may also use ext-yaml when both its parser
 * and emitter are available. Configuration Manager deliberately has no
 * hand-written production YAML serializer: an incomplete serializer can make
 * an export look successful while writing data which cannot be parsed back.
 */
class SimpleYaml {
  private static bool $runtimeAutoloadAttempted = FALSE;

  /**
   * @param array<string|int, mixed> $data
   */
  public static function dump(array $data): string {
    if (self::loadSymfonyYaml()) {
      return self::normaliseYamlOutput(\Symfony\Component\Yaml\Yaml::dump($data, 8, 2));
    }

    if (function_exists('yaml_emit')) {
      try {
        $yaml = self::callWithoutPhpWarning(static function() use ($data) {
          return yaml_emit($data);
        }, 'YAML serialization failed');
      }
      catch (\Throwable $e) {
        throw new \RuntimeException('Could not serialize Configuration Manager YAML with ext-yaml: ' . $e->getMessage(), 0, $e);
      }
      if (!is_string($yaml) || $yaml === '') {
        throw new \RuntimeException('Could not serialize Configuration Manager YAML with ext-yaml.');
      }
      return self::normaliseYamlOutput($yaml);
    }

    throw new \RuntimeException(
      'No safe YAML dumper is available. Install the Configuration Manager release package with its bundled Symfony YAML runtime, run Composer for a source checkout, or enable the PHP yaml extension with yaml_emit().'
    );
  }

  /**
   * Normalise YAML generated by different libraries so exported files stay
   * easier to read and do not switch between `~` and `null` for empty values.
   */
  private static function normaliseYamlOutput(string $yaml): string {
    $yaml = preg_replace('/^---\s*\R/', '', $yaml);
    $yaml = preg_replace('/\R\.\.\.\s*$/', "\n", $yaml);
    $yaml = preg_replace('/(:\s*)~(\s*(?:#.*)?$)/m', '$1null$2', $yaml);
    $yaml = preg_replace('/(^\s*-\s*)~(\s*(?:#.*)?$)/m', '$1null$2', $yaml);
    return rtrim((string) $yaml) . "\n";
  }

  /**
   * Report the complete YAML read/write runtime available to web/CLI.
   *
   * `available` means Configuration Manager can both parse and emit YAML. A
   * parser-only extension is not enough because Export must never fall back to
   * an incomplete serializer.
   *
   * @return array{available:bool,parser:string,dumper:string,reason:string,symfony_yaml_available:bool,extension_vendor_autoload:bool,php_yaml_extension:bool,php_yaml_emitter:bool}
   */
  public static function runtimeStatus(): array {
    $autoload = dirname(__DIR__, 3) . '/vendor/autoload.php';
    $extensionVendorAutoload = is_file($autoload);
    $phpYamlExtension = function_exists('yaml_parse_file');
    $phpYamlEmitter = function_exists('yaml_emit');
    $symfonyYamlAvailable = self::loadSymfonyYaml();

    if ($symfonyYamlAvailable) {
      return [
        'available' => TRUE,
        'parser' => 'symfony/yaml',
        'dumper' => 'symfony/yaml',
        'reason' => '',
        'symfony_yaml_available' => TRUE,
        'extension_vendor_autoload' => $extensionVendorAutoload,
        'php_yaml_extension' => $phpYamlExtension,
        'php_yaml_emitter' => $phpYamlEmitter,
      ];
    }

    if ($phpYamlExtension && $phpYamlEmitter) {
      return [
        'available' => TRUE,
        'parser' => 'ext-yaml',
        'dumper' => 'ext-yaml',
        'reason' => '',
        'symfony_yaml_available' => FALSE,
        'extension_vendor_autoload' => $extensionVendorAutoload,
        'php_yaml_extension' => TRUE,
        'php_yaml_emitter' => TRUE,
      ];
    }

    $reason = 'No complete YAML runtime is available. Install the Configuration Manager release package with its bundled Symfony YAML runtime, run Composer for a source checkout, or enable the PHP yaml extension.';
    if ($phpYamlExtension && !$phpYamlEmitter) {
      $reason = 'The PHP yaml extension can parse YAML but yaml_emit() is unavailable, so Configuration Manager cannot safely export YAML. Install the bundled Symfony YAML runtime or enable a complete ext-yaml build.';
    }

    return [
      'available' => FALSE,
      'parser' => $phpYamlExtension ? 'ext-yaml' : '',
      'dumper' => '',
      'reason' => $reason,
      'symfony_yaml_available' => FALSE,
      'extension_vendor_autoload' => $extensionVendorAutoload,
      'php_yaml_extension' => $phpYamlExtension,
      'php_yaml_emitter' => $phpYamlEmitter,
    ];
  }

  /**
   * @return array<string|int, mixed>
   */
  public static function parseFile(string $file): array {
    if (self::loadSymfonyYaml()) {
      try {
        $data = \Symfony\Component\Yaml\Yaml::parseFile($file);
      }
      catch (\Throwable $e) {
        throw new \RuntimeException('Could not parse YAML file ' . $file . ': ' . $e->getMessage(), 0, $e);
      }
      return is_array($data) ? $data : [];
    }

    if (function_exists('yaml_parse_file')) {
      try {
        $data = self::callWithoutPhpWarning(static function() use ($file) {
          return yaml_parse_file($file);
        }, 'YAML parsing failed');
      }
      catch (\Throwable $e) {
        throw new \RuntimeException('Could not parse YAML file ' . $file . ': ' . $e->getMessage(), 0, $e);
      }
      if ($data === FALSE) {
        throw new \RuntimeException('Could not parse YAML file ' . $file . '.');
      }
      return is_array($data) ? $data : [];
    }

    throw new \RuntimeException(
      'No YAML parser is available. Configuration Manager requires its bundled Symfony YAML runtime dependency or the PHP yaml extension.'
    );
  }

  /**
   * Load the extension-local Composer autoloader when the host application has
   * not already made Symfony YAML available.
   */
  private static function loadSymfonyYaml(): bool {
    if (class_exists('Symfony\\Component\\Yaml\\Yaml')) {
      return TRUE;
    }

    if (!self::$runtimeAutoloadAttempted) {
      self::$runtimeAutoloadAttempted = TRUE;
      $autoload = dirname(__DIR__, 3) . '/vendor/autoload.php';
      if (is_file($autoload)) {
        require_once $autoload;
      }
    }

    return class_exists('Symfony\\Component\\Yaml\\Yaml');
  }

  /**
   * Convert warnings from ext-yaml into exceptions before they can leak HTML or
   * warning text into JSON/CLI responses.
   *
   * @return mixed
   */
  private static function callWithoutPhpWarning(callable $callback, string $fallbackMessage) {
    set_error_handler(static function(int $severity, string $message, string $file = '', int $line = 0): bool {
      if (!(error_reporting() & $severity)) {
        return FALSE;
      }
      throw new \ErrorException($message, 0, $severity, $file, $line);
    });

    try {
      return $callback();
    }
    catch (\Throwable $e) {
      if ($e instanceof \ErrorException) {
        throw $e;
      }
      throw new \RuntimeException($fallbackMessage . ': ' . $e->getMessage(), 0, $e);
    }
    finally {
      restore_error_handler();
    }
  }
}
